# Generated by Django 4.2.6 on 2024-01-21 03:41

import ckeditor.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('fadil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tanggal_upload',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner', verbose_name='Gambar (575 x 200 pixel)'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='banner_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[575, 200], upload_to='gambar/banner', verbose_name='Gambar (575 x 200 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_dua',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_empat',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_lima',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_satu',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='gambar_tiga',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[270, 250], upload_to='gambar/banner', verbose_name='Gambar (270 x 250 pixel)'),
        ),
        migrations.AlterField(
            model_name='produk',
            name='keterangan_barang',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gambar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1200], upload_to='gambar/banner', verbose_name='Gambar (1920 x 1200 pixel)'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='keterangan',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='gambar_slide',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=80, scale=None, size=[880, 475], upload_to='gambar/banner', verbose_name='Gambar (475 x 880 pixel)'),
        ),
    ]
